// generate-photos.js
require('dotenv').config({ path: '.env.local' });
const cloudinary = require('cloudinary').v2;
const fs = require('fs');
const path = require('path');

// Connect to your Cloudinary account
cloudinary.config({
  cloud_name: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

async function run() {
  console.log('Fetching photos from Cloudinary...');

  try {
    // Search for all images in the "portfolio" folder
    // Max results is set to 100 to easily capture your 48 photos
    const results = await cloudinary.search
      .expression('folder:portfolio') 
      .max_results(100)
      .execute();

    if (results.resources.length === 0) {
      console.log('No photos found! Check your folder name.');
      return;
    }

    // Transform the data into the exact format your Next.js gallery needs
    const photosData = results.resources.map((img) => ({
      src: img.public_id,
      width: img.width,
      height: img.height,
      alt: "Skilled Plumbing Services - Recent Work",
    }));

    // Convert the Javascript object back into a string we can save as a .ts file
    const fileContent = `// Auto-generated by generate-photos.js\n\nexport const photos = ${JSON.stringify(photosData, null, 2)};\n`;

    // Save it directly over your existing data/photos.ts file
    const filePath = path.join(__dirname, 'data', 'photos.ts');
    fs.writeFileSync(filePath, fileContent);

    console.log(`✅ Success! Wrote ${photosData.length} photos to data/photos.ts`);

  } catch (error) {
    console.error('Failed to generate photos:', error);
  }
}

run();